name: Build APK for Kivy App

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            openjdk-11-jdk \
            unzip \
            zip \
            zlib1g-dev \
            libncurses5:i386 \
            libstdc++6:i386 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            libgstreamer1.0 \
            libgstreamer-plugins-base1.0 \
            curl

      - name: Upgrade pip and install buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Initialize buildozer (download android sdk/ndk etc)
        run: |
          buildozer android clean || true
          buildozer android debug

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
