name: Build APK with Buildozer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            git \
            openjdk-11-jdk \
            zip \
            unzip \
            zlib1g-dev \
            libncurses5:i386 \
            libstdc++6:i386 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            libgstreamer1.0 \
            libgstreamer-plugins-base1.0

      - name: Upgrade pip and install buildozer + cython
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk
